### ISSUE TITLE
Current master does not seem to compile

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360bdpImportService#6]
It seems like the current master does not compile with sw360 at version 3.1.0-SNAPSHOT (besides that current master seems to require `2.1.0-SNAPSHOT`, I changed that in order to come to this point):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project src-bdpimport: Compilation failure
[ERROR] /home/siemagrant/sw360bdpImportService/src-bdpimport/src/main/java/com/bosch/osmi/sw360/bdp/service/BdpImportHandler.java:[34,8] com.bosch.osmi.sw360.bdp.service.BdpImportHandler is not abstract and does not override abstract method suggestImportables(org.eclipse.sw360.datahandler.thrift.bdpimport.RemoteCredentials,java.lang.String) in org.eclipse.sw360.datahandler.thrift.bdpimport.BdpImportService.Iface
```

seems to be closed by #4

**Comment by bodetc** [comment]
I have updated the version to `3.2.0-SNAPSHOT` to work with current master in SW360.
Furthermore the release `3.1.0` works with the same release of SW360.
See https://github.com/sw360/sw360portal/releases/tag/sw360-3.1.0
